#ifndef __PUBLIC_LIBBSTTYPES_H
#define __PUBLIC_LIBBSTTYPES_H
/**************************************************************************
COPYRIGHT 2009 ACTISENSE - ACTIVE RESEARCH LTD. ALL RIGHTS RESERVED
WARNING - This file has been autogenerated by an Actisense "Wizard"
DO NOT EDIT AS ANY CHANGES WILL BE LOST IF THE FILE IS REGENERATED

This file is a private Actisense creative asset

Do not copy this source file to customers or co-developers
All rights reserved Actisense & Active Research Limited
----------------------------------------------------------------------------
Pathname: "C:\Work\Library\Wizards\BST\Public\LibBSTTypes.h"
Filename: "Public\LibBSTTypes.h"
----------------------------------------------------------------------------
Date: 27/01/2010 
Time: 10:09:37
****************************************************************************/

/***************************************************************************
Dependent Includes :
****************************************************************************/

/***************************************************************************
 Decode Data types :
 A set of unique codes used by the API to signify the type of data that has
 been transmitted or received. Codes that end in 0xFE do not have a sub-ID,
 only a BST ID (given by the top 8-bits), and are legacy message codes
****************************************************************************/
#ifndef __BST_TYPEDECODE_CORE__
    #define __BST_TYPEDECODE_CORE__
    
    typedef enum DecodeData_t {
    /*----------------------------------------------------------------------
     ARL BST/BEM Embedded Commands :
     All commands sent from the PC using BEM-ID code BST_BEMP_MSG_PG (0xA1),
     will use BEM-ID code BST_BEMP_MSG_GP (0xA0) for all required responses
     (ACKnowledge / NACKnowldege or Information), plus the BEM sub-command.
    -----------------------------------------------------------------------*/
    
    /* BST-BEM Re-Boot Hardware command/response */
    ddReBootPG                  = 0x11FE,
    
    
    /*---  Action sub-commands 0x00-0x0F  ---------------------------------*/
    /*----------------------------------------------------------------------
      Action commands used to trigger major operating mode changes on the
      attached device. Only to be used if the consequences are understood.
    -----------------------------------------------------------------------*/
    
    /* BST-BEM Re-Initialisation of Main Application command response */
    ddReInitMainApp             = 0xA000,
    
    /* BST-BEM Commit (changed configuration) To EEPROM command response */
    ddCommitToEEPROM            = 0xA001,
    
    /* BST-BEM Commit (changed configuration) To Flash ROM command response */
    ddCommitToFlash             = 0xA002,
    
    
    /*---  Request sub-commands 0x10-0xEF  --------------------------------*/
    /*----------------------------------------------------------------------
      Request commands either change settings on attached device, or query
      information/settings stored inside the attached device.
      Commands sent with no data/parameters are trigger requests for the
      attached device to send back the requested information.
      Commands with optional data/parameters not included will request that
      the attached device uses its built-in default values to complete the
      required request.
    -----------------------------------------------------------------------*/
    
    /* BST-BEM Request Hardware Information command response */
    ddHardwareInfo              = 0xA010,
    
    /* BST-BEM Request/Change Operating Mode command response */
    ddOperatingMode             = 0xA011,
    
    /* BST-BEM Request/Change Port Baud rates command response */
    ddPortBaudCfg               = 0xA012,
    
    /* BST-BEM Request/Change Port P-Code enables command response */
    ddPortPCodeCfg              = 0xA013,
    
    /* BST-BEM Request/Change Port 'Duplicate Deletion' enables command response */
    ddPortDupDelete             = 0xA014,
    
    /* BST-BEM Request/Change Total (Operating) Time command response */
    ddTotalTime                 = 0xA015,
    
    /* BST-BEM Request/Change Hardware Baud rates command response */
    ddHardwareBaud              = 0xA016,
    
    /* BST-BEM Request NMEA 2000 Product Information command response */
    ddProductInfoN2K            = 0xA041,
    
    /* BST-BEM Request/Change (NMEA 2000) CAN Config command response */
    ddCANConfig                 = 0xA042,
    
    /* BST-BEM Request/Change (NMEA 2000) CAN Information Field 1 command response */
    ddCANInfoField1             = 0xA043,
    
    /* BST-BEM Request/Change (NMEA 2000) CAN Information Field 2 command response */
    ddCANInfoField2             = 0xA044,
    
    /* BST-BEM Request (NMEA 2000) CAN Information Field 3 command response */
    ddCANInfoField3             = 0xA045,
    
    /* BST-BEM Request/Change an Rx PGN Enable status command response */
    ddEnableRxPGN               = 0xA046,
    
    /* BST-BEM Request/Change an Tx PGN Enable status command response */
    ddEnableTxPGN               = 0xA047,
    
    /* BST-BEM Request Rx PGN Enable List command response */
    ddRxPGNEnableList           = 0xA048,
    
    /* BST-BEM Request Tx PGN Enable List command response */
    ddTxPGNEnableList           = 0xA049,
    
    /* BST-BEM Request to Delete a PGN Enable List command response */
    ddDeletePGNEnableList       = 0xA04A,
    
    /* BST-BEM Request to Activate a PGN Enable List command response */
    ddActivatePGNEnableLists    = 0xA04B,
    
    /* BST-BEM Request to Set a Default PGN Enable List command response */
    ddDefaultPGNEnableList      = 0xA04C,
    
    /* BST-BEM Request PGN Enable List Parameters command response */
    ddParamsPGNEnableLists      = 0xA04D,
    
    
    /*---  Report sub-commands 0xF0-0xFC  ---------------------------------*/
    /*----------------------------------------------------------------------
      Report data is sent by the attached device whenever a trigger event
      occurs. This can be during startup, when an error's detected or at
      a specific interval (e.g. system status once per second). The user
      cannot request these messages.
    -----------------------------------------------------------------------*/
    
    /* BST-BEM 'Startup Status' information report */
    ddStartupStatus             = 0xA0F0,
    
    /* BST-BEM 'Error Status' information report */
    ddErrorReport               = 0xA0F1,
    
    /* BST-BEM 'System Status' information report */
    ddSystemStatus              = 0xA0F2,
    
    /* BST-BEM Confirm Software Reset command response */
    ddConfirmSoftwareReset      = 0xA0F3,
    
    /* BST-BEM Negative Acknowledgement report */
    ddNegativeAcknowledge       = 0xA0F4,
    
    
    /*---  Action sub-commands 0x00-0x0F  ---------------------------------*/
    /*----------------------------------------------------------------------
      Action commands used to trigger major operating mode changes on the
      attached device. Only to be used if the consequences are understood.
    -----------------------------------------------------------------------*/
    
    /* BST-BEM Re-Initialisation of Main Application command */
    ddReInitMainAppPG           = 0xA100,
    
    /* BST-BEM Commit (changed configuration) To EEPROM command */
    ddCommitToEEPROMPG          = 0xA101,
    
    /* BST-BEM Commit (changed configuration) To Flash ROM command */
    ddCommitToFlashPG           = 0xA102,
    
    
    /*---  Request sub-commands 0x10-0xEF  --------------------------------*/
    /*----------------------------------------------------------------------
      Request commands either change settings on attached device, or query
      information/settings stored inside the attached device.
      Commands sent with no data/parameters are trigger requests for the
      attached device to send back the requested information.
      Commands with optional data/parameters not included will request that
      the attached device uses its built-in default values to complete the
      required request.
    -----------------------------------------------------------------------*/
    
    /* BST-BEM Request Hardware Information command */
    ddHardwareInfoPG            = 0xA110,
    
    /* BST-BEM Request/Change Operating Mode command */
    ddOperatingModePG           = 0xA111,
    
    /* BST-BEM Request/Change Port Baud rates command */
    ddPortBaudCfgPG             = 0xA112,
    
    /* BST-BEM Request/Change Port P-Code enables command */
    ddPortPCodeCfgPG            = 0xA113,
    
    /* BST-BEM Request/Change Port 'Duplicate Deletion' enables command */
    ddPortDupDeletePG           = 0xA114,
    
    /* BST-BEM Request/Change Total (Operating) Time command */
    ddTotalTimePG               = 0xA115,
    
    /* BST-BEM Request/Change Hardware Baud rates command */
    ddHardwareBaudPG            = 0xA116,
    
    /* BST-BEM Request NMEA 2000 Product Information command */
    ddProductInfoN2KPG          = 0xA141,
    
    /* BST-BEM Request/Change (NMEA 2000) CAN Config command */
    ddCANConfigPG               = 0xA142,
    
    /* BST-BEM Request/Change (NMEA 2000) CAN Information Field 1 command */
    ddCANInfoField1PG           = 0xA143,
    
    /* BST-BEM Request/Change (NMEA 2000) CAN Information Field 2 command */
    ddCANInfoField2PG           = 0xA144,
    
    /* BST-BEM Request (NMEA 2000) CAN Information Field 3 command */
    ddCANInfoField3PG           = 0xA145,
    
    /* BST-BEM Request/Change an Rx PGN Enable status command */
    ddEnableRxPGNPG             = 0xA146,
    
    /* BST-BEM Request/Change an Tx PGN Enable status command */
    ddEnableTxPGNPG             = 0xA147,
    
    /* BST-BEM Request Rx PGN Enable List command */
    ddRxPGNEnableListPG         = 0xA148,
    
    /* BST-BEM Request Tx PGN Enable List command */
    ddTxPGNEnableListPG         = 0xA149,
    
    /* BST-BEM Request to Delete a PGN Enable List command */
    ddDeletePGNEnableListPG     = 0xA14A,
    
    /* BST-BEM Request to Activate a PGN Enable List command */
    ddActivatePGNEnableListsPG  = 0xA14B,
    
    /* BST-BEM Request to Set a Default PGN Enable List command */
    ddDefaultPGNEnableListPG    = 0xA14C,
    
    /* BST-BEM Request PGN Enable List Parameters command */
    ddParamsPGNEnableListsPG    = 0xA14D,
    
    
    /*---  BEM Debug Protocol Status --------------------------------------*/
    /*----------------------------------------------------------------------
      All Debug messages are sent from the Product using BEM Sub-ID code
      BST_BEMP_DBG_GP (0xA2)
    -----------------------------------------------------------------------*/
    
    /*---  Non-specific sub-commands 0x00-0x1F  ---------------------------*/
    /*----------------------------------------------------------------------
      Common debug codes - should not be product or software specific
    -----------------------------------------------------------------------*/
    
    /* BST-BEM 'Text string' Debug report */
    ddDebugText                 = 0xA200,
    
    /* BST-BEM 'U32 Value' Debug report */
    ddDebugValueU32             = 0xA201,
    
    /* BST-BEM 'S32 Value' Debug report */
    ddDebugValueS32             = 0xA202,
    
    
    /*---  Specific sub-commands 0x20-0x3F  -------------------------------*/
    /*----------------------------------------------------------------------
      Project/Hardware type specific program codes - specific to a
      particular products, product group types or hardware types.
      No need to group codes into areas: new codes assigned as necessary
      wherever the standard codes are not workable for a new use.
    -----------------------------------------------------------------------*/
    
    /* BST-BEM 'Time Profiler' Debug report */
    ddDebugTimeProfiler         = 0xA220,
    
    /* End of Enumeration */
    ddLastEnum                  = 0xFFFD,
    

} DecodeData_t;

#endif

/***************************************************************************
 Decode Data types quick copy list :
 Concise list of all the dd types above as an easy 'copy'n'paste' reference
 when creating a C array definition (instead of using enum definition above)
****************************************************************************/
#if 0
   /* BST-BEM Re-Initialisation of Main Application command response */
   ddReInitMainApp,
   /* BST-BEM Commit (changed configuration) To EEPROM command response */
   ddCommitToEEPROM,
   /* BST-BEM Commit (changed configuration) To Flash ROM command response */
   ddCommitToFlash,
   /* BST-BEM Request Hardware Information command response */
   ddHardwareInfo,
   /* BST-BEM Request/Change Operating Mode command response */
   ddOperatingMode,
   /* BST-BEM Request/Change Port Baud rates command response */
   ddPortBaudCfg,
   /* BST-BEM Request/Change Port P-Code enables command response */
   ddPortPCodeCfg,
   /* BST-BEM Request/Change Port 'Duplicate Deletion' enables command response */
   ddPortDupDelete,
   /* BST-BEM Request/Change Total (Operating) Time command response */
   ddTotalTime,
   /* BST-BEM Request/Change Hardware Baud rates command response */
   ddHardwareBaud,
   /* BST-BEM Request NMEA 2000 Product Information command response */
   ddProductInfoN2K,
   /* BST-BEM Request/Change (NMEA 2000) CAN Config command response */
   ddCANConfig,
   /* BST-BEM Request/Change (NMEA 2000) CAN Information Field 1 command response */
   ddCANInfoField1,
   /* BST-BEM Request/Change (NMEA 2000) CAN Information Field 2 command response */
   ddCANInfoField2,
   /* BST-BEM Request (NMEA 2000) CAN Information Field 3 command response */
   ddCANInfoField3,
   /* BST-BEM Request/Change an Rx PGN Enable status command response */
   ddEnableRxPGN,
   /* BST-BEM Request/Change an Tx PGN Enable status command response */
   ddEnableTxPGN,
   /* BST-BEM Request Rx PGN Enable List command response */
   ddRxPGNEnableList,
   /* BST-BEM Request Tx PGN Enable List command response */
   ddTxPGNEnableList,
   /* BST-BEM Request to Delete a PGN Enable List command response */
   ddDeletePGNEnableList,
   /* BST-BEM Request to Activate a PGN Enable List command response */
   ddActivatePGNEnableLists,
   /* BST-BEM Request to Set a Default PGN Enable List command response */
   ddDefaultPGNEnableList,
   /* BST-BEM Request PGN Enable List Parameters command response */
   ddParamsPGNEnableLists,
   /* BST-BEM 'Startup Status' information report */
   ddStartupStatus,
   /* BST-BEM 'Error Status' information report */
   ddErrorReport,
   /* BST-BEM 'System Status' information report */
   ddSystemStatus,
   /* BST-BEM Confirm Software Reset command response */
   ddConfirmSoftwareReset,
   /* BST-BEM Negative Acknowledgement report */
   ddNegativeAcknowledge,
   /* BST-BEM 'Text string' Debug report */
   ddDebugText,
   /* BST-BEM 'U32 Value' Debug report */
   ddDebugValueU32,
   /* BST-BEM 'S32 Value' Debug report */
   ddDebugValueS32,
   /* BST-BEM 'Time Profiler' Debug report */
   ddDebugTimeProfiler,
#endif
/***************************************************************************
 End of Decode Data types quick copy list
****************************************************************************/

/***************************************************************************
End Of Wizard Generated File "Public\LibBSTTypes.h"
****************************************************************************/
#endif /* __PUBLIC_LIBBSTTYPES_H */
